### ISSUE TITLE
随机多次点击几个不存在页面的路由后，提示信息会一次显示多条。

### ISSUE THREAD

**Issue by caopengfei** [wzxinchen/BlazAdmin#14]
![TIM图片20191224162225](https://user-images.githubusercontent.com/10126284/71403079-9a473180-2669-11ea-9a94-5080272c983c.png)
![TIM图片20191224162416](https://user-images.githubusercontent.com/10126284/71403189-edb97f80-2669-11ea-9ed8-1f25bfc01ab0.png)
另外，有时却又没有任何提示，感觉很任性哦。

**Comment by wzxinchen** [comment]
难以解决，已将该提示去掉
