### ISSUE TITLE
弹框中直接点击右上角的叉叉后, 调用弹框的方法无法继续执行

### ISSUE THREAD

**Issue by flysmallstrong** [wzxinchen/BlazAdmin#15]
var result = await DialogService.ShowDialogAsync<win, bool>("title", 550);
    if (result.Result)
   
弹框中直接点击右上角的叉叉后, 调用弹框的方法无法获得result.Result的bool类型的值.

**Comment by wzxinchen** [comment]
这个问题随 Blazui 版本发布来修复
